[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  # Explicitly tell Netlify to use npm as the package manager
  # This is a fallback in case other configurations are ignored
  NPM_PACKAGE_MANAGER = "npm"
  SECRETS_SCAN_ENABLED = "false"

# Domain redirects - handy2know.co.uk to handy2know.com
[[redirects]]
  from = "https://handy2know.co.uk/*"
  to = "https://handy2know.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://handy2know.co.uk/*"
  to = "https://handy2know.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.handy2know.co.uk/*"
  to = "https://handy2know.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.handy2know.co.uk/*"
  to = "https://handy2know.com/:splat"
  status = 301
  force = true

# WWW redirects
[[redirects]]
  from = "https://www.handy2know.com/*"
  to = "https://handy2know.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.handy2know.com/*"
  to = "https://handy2know.com/:splat"
  status = 301
  force = true

# Force HTTPS
[[redirects]]
  from = "http://handy2know.com/*"
  to = "https://handy2know.com/:splat"
  status = 301
  force = true

# SPA fallback for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"



# Forced build to clear cache and re-evaluate settings

