backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Meta Description", name: "metaDescription", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featuredImage", widget: "image", required: false}
      - {label: "Published", name: "published", widget: "boolean", default: true}

  - name: "home"
    label: "Home Page"
    files:
      - label: "Home Page Content"
        name: "home"
        file: "src/content/home.md"
        fields:
          - {label: "Hero Title", name: "heroTitle", widget: "string"}
          - {label: "Hero Subtitle", name: "heroSubtitle", widget: "text"}
          - {label: "Hero CTA Text", name: "heroCTA", widget: "string"}
          - {label: "Features Section Title", name: "featuresTitle", widget: "string"}
          - label: "Features"
            name: "features"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Icon", name: "icon", widget: "string"}
          - {label: "About Section Title", name: "aboutTitle", widget: "string"}
          - {label: "About Section Content", name: "aboutContent", widget: "markdown"}

  - name: "testimonials"
    label: "Testimonials"
    folder: "src/content/testimonials"
    create: true
    slug: "{{name}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Company", name: "company", widget: "string", required: false}
      - {label: "Testimonial", name: "testimonial", widget: "text"}
      - {label: "Rating", name: "rating", widget: "number", min: 1, max: 5}
      - {label: "Photo", name: "photo", widget: "image", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "pricing"
    label: "Pricing Plans"
    files:
      - label: "Pricing Configuration"
        name: "pricing"
        file: "src/content/pricing.md"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Page Subtitle", name: "subtitle", widget: "text"}
          - label: "Plans"
            name: "plans"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Price", name: "price", widget: "string"}
              - {label: "Period", name: "period", widget: "string"}
              - {label: "Credits", name: "credits", widget: "number"}
              - {label: "Stripe Price ID", name: "stripePriceId", widget: "string"}
              - {label: "Popular", name: "popular", widget: "boolean", default: false}
              - label: "Features"
                name: "features"
                widget: "list"
                field: {label: "Feature", name: "feature", widget: "string"}

  - name: "trades"
    label: "Trade Profiles"
    folder: "src/content/trades"
    create: true
    slug: "{{name}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Business Name", name: "businessName", widget: "string"}
      - {label: "Trade Type", name: "tradeType", widget: "select", options: ["Plumber", "Electrician", "Carpenter", "Builder", "Painter", "Roofer", "Gardener", "Other"]}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Phone", name: "phone", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Experience Years", name: "experienceYears", widget: "number"}
      - {label: "Rating", name: "rating", widget: "number", min: 1, max: 5, step: 0.1}
      - {label: "Profile Photo", name: "profilePhoto", widget: "image", required: false}
      - label: "Services"
        name: "services"
        widget: "list"
        field: {label: "Service", name: "service", widget: "string"}
      - label: "Certifications"
        name: "certifications"
        widget: "list"
        field: {label: "Certification", name: "certification", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "src/content/settings.md"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - {label: "Site Description", name: "siteDescription", widget: "text"}
          - {label: "Contact Email", name: "contactEmail", widget: "string"}
          - {label: "Contact Phone", name: "contactPhone", widget: "string"}
          - {label: "Address", name: "address", widget: "text"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Favicon", name: "favicon", widget: "image"}
          - label: "Social Media"
            name: "socialMedia"
            widget: "object"
            fields:
              - {label: "Facebook", name: "facebook", widget: "string", required: false}
              - {label: "Twitter", name: "twitter", widget: "string", required: false}
              - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
              - {label: "Instagram", name: "instagram", widget: "string", required: false}

  - name: "navigation"
    label: "Navigation"
    files:
      - label: "Main Navigation"
        name: "navigation"
        file: "src/content/navigation.md"
        fields:
          - label: "Main Menu"
            name: "mainMenu"
            widget: "list"
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "External", name: "external", widget: "boolean", default: false}
          - label: "Footer Menu"
            name: "footerMenu"
            widget: "list"
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "External", name: "external", widget: "boolean", default: false}
